# Generated by Django 3.2.8 on 2021-11-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211105_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Welcome Home', max_length=100),
        ),
    ]
